schemaVersion: '2.0.0'
commandTests:
  - name: "node installation"
    command: "which"
    args: ["node"]
    expectedOutput: ["/usr/local/bin/node\n"]

  - name: "node version"
    command: "node"
    args: ["--version"]
    expectedOutput: ["v10.*\n"]

  - name: "ssh client installation"
    command: "which"
    args: ["ssh"]
    expectedOutput: ["/usr/bin/ssh\n"]
