schemaVersion: '2.0.0'
commandTests:
  - name: "node installation"
    command: "node"
    args: ["--version"]
    expectedOutput: ["v10.*\n"]

  - name: "ssh client installation"
    command: "which"
    args: ["ssh"]
    expectedOutput: ["/usr/bin/ssh\n"]

  - name: "make installation"
    command: "make"
    args: ["--version"]
    expectedOutput: ["GNU Make 4.2.*"]
